### ISSUE TITLE
CoreCLR support

### ISSUE THREAD

**Issue by ivanz** [CorrelatorSharp/CorrelatorSharp#10]

**Comment by ugumba** [comment]
Any chance of this going forward?
Maybe I can help - I've ported CorrelationIdActionFilterAttribute to ASP.NET Core, which was easy enough.

This is a great little library, but it looks like activity has tapered off - is there some alternative I'm not aware of yet?

**Comment by ivanz** [comment]
Hey, I was busy porting MSpec to .NET Core and haven't got around to it. There should be zero or barely any code changes required and the work is mostly around 1) Adopting project.json and xproj and 2) updating the CI+CD pipeline (I was going to use something similar to what was done in Mspec: https://github.com/machine/machine.specifications/blob/master/appveyor.yml )

Let me know if you want to take any of this work to avoid duplicate work :)

**Comment by ivanz** [comment]
Starting from 1.4.0-beta1 CorrelatorSharp is now .NET Standard 1.3+
