### ISSUE TITLE
Using static variable for stack

### ISSUE THREAD

**Issue by thinkthencode** [CorrelatorSharp/CorrelatorSharp#21]
I'm little confused about usage of static variables in Tracker. Will that not cause conflict for multiple request sharing same variable?

**Comment by ivanz** [comment]
It uses [AsyncLocal<T>](https://msdn.microsoft.com/en-us/library/dn906268(v=vs.110).aspx) under the hood in order to flow the context across threads and/or task async flows, so even though it's static - the value is not.
