### ISSUE TITLE
Use with Exception Filter in Web API

### ISSUE THREAD

**Issue by StuartFergusonPC1** [CorrelatorSharp/CorrelatorSharp#25]
I have just started using this in our ASP.Net WebAPI projects and have noticed when I call "ActivityScope currentActivity = ActivityScope.Current;" in an Exception Filter that this returns null.

Is there something I am doing wrong that this is not persisted ?

**Comment by jasond-s** [comment]
You will need to use the CorrelatorSharp filter before any other filters that might want to use the `ActivityScope.Current`, to ensure it is set up.

Your filters setup should look something like this:

```
config.Filters.Add(new CorrelationIdActionFilter());
config.Filters.Add(new RequestLoggerActionFilter());
```
